# -*- coding: utf-8 -*-
"""POL-4 — model throughput benchmark. Measures generation tok/s (and prompt eval tok/s) for an Ollama
model on this machine, using Ollama's own timing fields. Writes docs/32b-throughput.md.

Usage:  python scripts/bench_model.py [--model qwen2.5:32b] [--runs 2] [--num-predict 200] [--write-doc]
Requires Ollama running with the model pulled.
"""
import argparse
import json
import sys
import time
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from config import OLLAMA  # noqa: E402

PROMPT = "Explain how a CPU pipeline works, then list three optimization techniques. Be concise."


def bench(model, num_predict):
    body = json.dumps({"model": model, "prompt": PROMPT, "stream": False,
                       "options": {"num_predict": num_predict}}).encode()
    rq = urllib.request.Request(OLLAMA + "/api/generate", data=body,
                                headers={"Content-Type": "application/json"}, method="POST")
    t0 = time.time()
    with urllib.request.urlopen(rq, timeout=900) as r:
        j = json.loads(r.read().decode())
    wall = time.time() - t0
    ec, ed = j.get("eval_count", 0), (j.get("eval_duration") or 1)
    pc, pd = j.get("prompt_eval_count", 0), (j.get("prompt_eval_duration") or 1)
    return {"gen_tokens": ec, "tok_s": round(ec / (ed / 1e9), 1),
            "prompt_tokens": pc, "prompt_tok_s": round(pc / (pd / 1e9), 1),
            "wall_s": round(wall, 1), "load_s": round((j.get("load_duration") or 0) / 1e9, 1)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="qwen2.5:32b")
    ap.add_argument("--runs", type=int, default=2)
    ap.add_argument("--num-predict", type=int, default=200)
    ap.add_argument("--write-doc", action="store_true")
    args = ap.parse_args()

    print(f"Benchmarking {args.model} (warmup + {args.runs} runs, {args.num_predict} tokens each)…")
    try:
        warm = bench(args.model, 16)  # warmup loads the model into VRAM
        print(f"  warmup: load {warm['load_s']}s")
    except Exception as e:
        print("ERROR:", e); return 1

    runs = []
    for i in range(args.runs):
        r = bench(args.model, args.num_predict)
        runs.append(r)
        print(f"  run {i+1}: {r['tok_s']} tok/s gen ({r['gen_tokens']} tok), "
              f"{r['prompt_tok_s']} tok/s prompt, wall {r['wall_s']}s")
    best = max(runs, key=lambda r: r["tok_s"])
    avg = round(sum(r["tok_s"] for r in runs) / len(runs), 1)
    print(f"\n=== {args.model}: best {best['tok_s']} tok/s, avg {avg} tok/s (gen) ===")

    if args.write_doc:
        ts = datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M %Z")
        lines = [
            "# Model throughput benchmark (POL-4)", "",
            f"_Generated by `scripts/bench_model.py` on {ts}._", "",
            f"Generation throughput for **{args.model}** on this machine (RTX 5090), measured via "
            "Ollama's own `eval_count`/`eval_duration`.", "",
            f"**Best {best['tok_s']} tok/s · avg {avg} tok/s** (generation) · "
            f"prompt eval ~{best['prompt_tok_s']} tok/s · model load {warm['load_s']}s.", "",
            "| Run | Gen tok/s | Gen tokens | Prompt tok/s | Wall s |",
            "|---|---|---|---|---|",
        ]
        for i, r in enumerate(runs, 1):
            lines.append(f"| {i} | {r['tok_s']} | {r['gen_tokens']} | {r['prompt_tok_s']} | {r['wall_s']} |")
        lines += ["", "Re-run: `python scripts/bench_model.py --model <name> --write-doc`.", ""]
        (ROOT / "docs" / "32b-throughput.md").write_text("\n".join(lines), encoding="utf-8")
        print("wrote docs/32b-throughput.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
